/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Abhi
 */
public class sic extends javax.swing.JFrame {

    /**
     * Creates new form sic
     */
    public sic() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        tf2 = new javax.swing.JTextField();
        tf3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        l4 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        l8 = new javax.swing.JLabel();
        l9 = new javax.swing.JLabel();
        l6 = new javax.swing.JLabel();
        l10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(450, 220));
        setName("f4"); // NOI18N
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("D2D Calc..");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        l1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        l1.setForeground(new java.awt.Color(255, 0, 0));
        l1.setText("Principal");
        l1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        l2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        l2.setForeground(new java.awt.Color(255, 0, 0));
        l2.setText("Interest Rate");
        l2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        l3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        l3.setForeground(new java.awt.Color(255, 0, 0));
        l3.setText("Time Period");
        l3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf1ActionPerformed(evt);
            }
        });
        tf1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf1KeyTyped(evt);
            }
        });

        tf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf2ActionPerformed(evt);
            }
        });
        tf2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf2KeyTyped(evt);
            }
        });

        tf3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf3KeyTyped(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Calculate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        l4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        l4.setText("Interest :");

        l5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        l5.setText("Amount Due :");

        jLabel2.setText("(Month)");

        jLabel3.setText("(Month)");

        l8.setText("0");

        l9.setText("0");

        l6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        l6.setText("EMI :");

        l10.setText("0");

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });

        jMenuBar1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 0, 153)));

        jMenu1.setText("Menu");
        jMenu1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_BACK_SPACE, 0));
        jMenuItem1.setText("Previous");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(l1)
                                    .addComponent(l2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tf2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel2))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(l4)
                                            .addComponent(l5)
                                            .addComponent(l6))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(l8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(l9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(l10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(l3)
                                        .addGap(18, 18, 18)
                                        .addComponent(tf3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel3)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(90, 90, 90))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l1)
                    .addComponent(tf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l3)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l4)
                    .addComponent(l8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l5)
                    .addComponent(l9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l6)
                    .addComponent(l10))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
      this.dispose();
      
      
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void tf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
if(tf1.getText().equals("")||tf2.getText().equals("")||tf3.getText().equals(""))
{

l8.setText("Null");
l9.setText("Null");
l10.setText("Null");

tf1.setText("");
tf2.setText("");
tf3.setText("");

tf1.requestFocus();




}       
       else
{
        Double a=Double.parseDouble(tf1.getText());
        Double b=Double.parseDouble(tf2.getText());
        Double c=Double.parseDouble(tf3.getText());
        
        Double d=a/100.0;
        Double e=d*b;
        Double f=e*c;
        
        l8.setText(String.valueOf(f));
        
        Double g=a+f;
        
        l9.setText(String.valueOf(g));
        
        Double h=g/c;    
        
        l10.setText(String.valueOf(h));
        
        
}       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        tf1.setText("");
        tf2.setText("");
        tf3.setText("");
        
        l8.setText("");
        l9.setText("");
        l10.setText("");
        
        tf1.requestFocus();
        
        
        
      
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new f2().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void tf1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf1KeyTyped
        // TODO add your handling code here:
          char caracter = evt.getKeyChar();
 
        int j=0;
        
    if(caracter=='a'||caracter=='b'||caracter=='c'||caracter=='d'||caracter=='e'||caracter=='f'||caracter=='g'||caracter=='h'||caracter=='i'||caracter=='j'||caracter=='k'||caracter=='l'||caracter=='m'||caracter=='n'||caracter=='o'||caracter=='p'||caracter=='q'||caracter=='r'||caracter=='s'||caracter=='t'||caracter=='u'||caracter=='v'||caracter=='w'||caracter=='x'||caracter=='y'||caracter=='z'||caracter=='`'||caracter=='~'||caracter=='!'||caracter=='@'||caracter=='#'||caracter=='$'||caracter=='%'||caracter=='^'||caracter=='&'||caracter=='*'||caracter=='-'||caracter=='_'||caracter=='='||caracter=='+'||caracter=='|'||caracter=='"'||caracter==';'||caracter==':'||caracter=='?'||caracter=='/'||caracter=='>'||caracter=='<'||caracter==','||caracter==')'||caracter=='A'||caracter=='B'||caracter=='C'||caracter=='D'||caracter=='E'||caracter=='F'||caracter=='G'||caracter=='H'||caracter=='I'||caracter=='J'||caracter=='K'||caracter=='L'||caracter=='M'||caracter=='N'||caracter=='O'||caracter=='P'||caracter=='Q'||caracter=='R'||caracter=='S'||caracter=='T'||caracter=='U'||caracter=='V'||caracter=='W'||caracter=='X'||caracter=='Y'||caracter=='Z')
    {
    
        evt.consume();
    }
    
        
        if((tf1.getText().equals(""))&&(caracter=='.'))
                {
               tf1.setText("0");
               tf1.requestFocus();
                
                }
        
        if(!(tf1.getText()).equals(""))
        {
      
        
            String s=tf1.getText();
            
            int l=s.length();
            
          for(int i=0;i<l;i++)
            {
            
            if(s.charAt(i)=='.')
            {
               j=1;  
           
            }
           
            
            
            }
 if(j==1 && caracter=='.')
 {
 
                 evt.consume();
 
 }
 else if (((caracter < '0') || (caracter > '9'))
                        &&(caracter != '\b')&&(caracter != '.')) 
              {
                   
                    evt.consume();
                    
                 
                }
  

                 
                }
        
        
    }//GEN-LAST:event_tf1KeyTyped

    private void tf2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf2KeyTyped
        // TODO add your handling code here:
        
            char caracter = evt.getKeyChar();
 
        int j=0;
        
    if(caracter=='a'||caracter=='b'||caracter=='c'||caracter=='d'||caracter=='e'||caracter=='f'||caracter=='g'||caracter=='h'||caracter=='i'||caracter=='j'||caracter=='k'||caracter=='l'||caracter=='m'||caracter=='n'||caracter=='o'||caracter=='p'||caracter=='q'||caracter=='r'||caracter=='s'||caracter=='t'||caracter=='u'||caracter=='v'||caracter=='w'||caracter=='x'||caracter=='y'||caracter=='z'||caracter=='`'||caracter=='~'||caracter=='!'||caracter=='@'||caracter=='#'||caracter=='$'||caracter=='%'||caracter=='^'||caracter=='&'||caracter=='*'||caracter=='-'||caracter=='_'||caracter=='='||caracter=='+'||caracter=='|'||caracter=='"'||caracter==';'||caracter==':'||caracter=='?'||caracter=='/'||caracter=='>'||caracter=='<'||caracter==','||caracter==')'||caracter=='A'||caracter=='B'||caracter=='C'||caracter=='D'||caracter=='E'||caracter=='F'||caracter=='G'||caracter=='H'||caracter=='I'||caracter=='J'||caracter=='K'||caracter=='L'||caracter=='M'||caracter=='N'||caracter=='O'||caracter=='P'||caracter=='Q'||caracter=='R'||caracter=='S'||caracter=='T'||caracter=='U'||caracter=='V'||caracter=='W'||caracter=='X'||caracter=='Y'||caracter=='Z')
    {
    
        evt.consume();
    }
    
        
        if((tf2.getText().equals(""))&&(caracter=='.'))
                {
               tf2.setText("0");
               tf2.requestFocus();
                
                }
        
        if(!(tf2.getText()).equals(""))
        {
      
        
            String s=tf2.getText();
            
            int l=s.length();
            
          for(int i=0;i<l;i++)
            {
            
            if(s.charAt(i)=='.')
            {
               j=1;  
           
            }
           
            
            
            }
 if(j==1 && caracter=='.')
 {
 
                 evt.consume();
 
 }
 else if (((caracter < '0') || (caracter > '9'))
                        &&(caracter != '\b')&&(caracter != '.')) 
              {
                   
                    evt.consume();
                    
                 
                }
  

                 
                }
    }//GEN-LAST:event_tf2KeyTyped

    private void tf3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf3KeyTyped
        // TODO add your handling code here:
        
    char caracter = evt.getKeyChar();
 
        int j=0;
        
    if(caracter=='a'||caracter=='b'||caracter=='c'||caracter=='d'||caracter=='e'||caracter=='f'||caracter=='g'||caracter=='h'||caracter=='i'||caracter=='j'||caracter=='k'||caracter=='l'||caracter=='m'||caracter=='n'||caracter=='o'||caracter=='p'||caracter=='q'||caracter=='r'||caracter=='s'||caracter=='t'||caracter=='u'||caracter=='v'||caracter=='w'||caracter=='x'||caracter=='y'||caracter=='z'||caracter=='`'||caracter=='~'||caracter=='!'||caracter=='@'||caracter=='#'||caracter=='$'||caracter=='%'||caracter=='^'||caracter=='&'||caracter=='*'||caracter=='-'||caracter=='_'||caracter=='='||caracter=='+'||caracter=='|'||caracter=='"'||caracter==';'||caracter==':'||caracter=='?'||caracter=='/'||caracter=='>'||caracter=='<'||caracter==','||caracter==')'||caracter=='A'||caracter=='B'||caracter=='C'||caracter=='D'||caracter=='E'||caracter=='F'||caracter=='G'||caracter=='H'||caracter=='I'||caracter=='J'||caracter=='K'||caracter=='L'||caracter=='M'||caracter=='N'||caracter=='O'||caracter=='P'||caracter=='Q'||caracter=='R'||caracter=='S'||caracter=='T'||caracter=='U'||caracter=='V'||caracter=='W'||caracter=='X'||caracter=='Y'||caracter=='Z')
    {
    
        evt.consume();
    }
    
        
        if((tf3.getText().equals(""))&&(caracter=='.'))
                {
               tf3.setText("0");
               tf3.requestFocus();
                
                }
        
        if(!(tf3.getText()).equals(""))
        {
      
        
            String s=tf3.getText();
            
            int l=s.length();
            
          for(int i=0;i<l;i++)
            {
            
            if(s.charAt(i)=='.')
            {
               j=1;  
           
            }
           
            
            
            }
 if(j==1 && caracter=='.')
 {
 
                 evt.consume();
 
 }
 else if (((caracter < '0') || (caracter > '9'))
                        &&(caracter != '\b')&&(caracter != '.')) 
              {
                   
                    evt.consume();
                    
                 
                }
  

                    
                 
                }        
        
    }//GEN-LAST:event_tf3KeyTyped

    private void tf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf2ActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed

        if(evt.getKeyCode()==evt.VK_ENTER)
        {
        
        if(tf1.getText().equals("")||tf2.getText().equals("")||tf3.getText().equals(""))
{

l8.setText("Null");
l9.setText("Null");
l10.setText("Null");

tf1.setText("");
tf2.setText("");
tf3.setText("");

tf1.requestFocus();




}       
       else
{
        Double a=Double.parseDouble(tf1.getText());
        Double b=Double.parseDouble(tf2.getText());
        Double c=Double.parseDouble(tf3.getText());
        
        Double d=a/100.0;
        Double e=d*b;
        Double f=e*c;
        
        l8.setText(String.valueOf(f));
        
        Double g=a+f;
        
        l9.setText(String.valueOf(g));
        
        Double h=g/c;    
        
        l10.setText(String.valueOf(h));
        
        
}       
        
        
        
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton1KeyPressed

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed
if(evt.getKeyCode()==evt.VK_ENTER)
{

 tf1.setText("");
        tf2.setText("");
        tf3.setText("");
        
        l8.setText("");
        l9.setText("");
        l10.setText("");
        
        tf1.requestFocus();


}
    }//GEN-LAST:event_jButton2KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sic().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l10;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel l8;
    private javax.swing.JLabel l9;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    private javax.swing.JTextField tf3;
    // End of variables declaration//GEN-END:variables
}
