/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Abhi
 */
public class tcon extends javax.swing.JFrame {

    /**
     * Creates new form tcon
     */
    public tcon() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        cb = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        l16 = new javax.swing.JLabel();
        l17 = new javax.swing.JLabel();
        l18 = new javax.swing.JLabel();
        l19 = new javax.swing.JLabel();
        l20 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        l12 = new javax.swing.JLabel();
        l13 = new javax.swing.JLabel();
        l14 = new javax.swing.JLabel();
        l15 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(450, 220));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("D2D Calc..");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(276, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        l1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l1.setForeground(new java.awt.Color(153, 0, 153));
        l1.setText("       Select Unit");
        l1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        cb.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Milliseconds", "Seconds", "Minutes", "Hours", "Days", "Weeks", "Month", "Years", "Centuries", " " }));
        cb.setToolTipText("Select Unit");
        cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Enter :");

        tf1.setText(" ");
        tf1.setToolTipText("Enter Value For Conversion");
        tf1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf1FocusLost(evt);
            }
        });
        tf1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                tf1InputMethodTextChanged(evt);
            }
        });
        tf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf1ActionPerformed(evt);
            }
        });
        tf1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf1KeyTyped(evt);
            }
        });

        b1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        b1.setText("-->");
        b1.setEnabled(false);
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        b1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                b1KeyPressed(evt);
            }
        });

        b2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        b2.setText("C");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        b2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                b2KeyPressed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Seconds :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Milliseconds :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Minutes :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Days :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("Hours :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("Weeks :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("Months :");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("Years :");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("Centuries :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l13)
                    .addComponent(l12)
                    .addComponent(l14)
                    .addComponent(l15)
                    .addComponent(l16)
                    .addComponent(l17)
                    .addComponent(l18)
                    .addComponent(l19)
                    .addComponent(l20))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(l12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(l13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(l14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(l15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(l16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(l17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(l18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(l19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(l20))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuBar1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 0, 153)));

        jMenu1.setText("Menu");
        jMenu1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_BACK_SPACE, 0));
        jMenuItem1.setText("Previous");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(43, 43, 43)
                        .addComponent(jLabel2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(b1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(b2)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l1)
                    .addComponent(jLabel2))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
     
        this.dispose();
        new f2().setVisible(true);
        
        
        
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

//Exit
        
        
        this.dispose();
        


// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbActionPerformed

    private void tf1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf1FocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_tf1FocusGained

    private void tf1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_tf1FocusLost

    private void tf1InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tf1InputMethodTextChanged

    }//GEN-LAST:event_tf1InputMethodTextChanged

    private void tf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf1ActionPerformed

    private void tf1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf1KeyTyped

        b1.setEnabled(true);
               
        char caracter = evt.getKeyChar();
 
        int j=0;
        
    if(caracter=='a'||caracter=='b'||caracter=='c'||caracter=='d'||caracter=='e'||caracter=='f'||caracter=='g'||caracter=='h'||caracter=='i'||caracter=='j'||caracter=='k'||caracter=='l'||caracter=='m'||caracter=='n'||caracter=='o'||caracter=='p'||caracter=='q'||caracter=='r'||caracter=='s'||caracter=='t'||caracter=='u'||caracter=='v'||caracter=='w'||caracter=='x'||caracter=='y'||caracter=='z'||caracter=='`'||caracter=='~'||caracter=='!'||caracter=='@'||caracter=='#'||caracter=='$'||caracter=='%'||caracter=='^'||caracter=='&'||caracter=='*'||caracter=='-'||caracter=='_'||caracter=='='||caracter=='+'||caracter=='|'||caracter=='"'||caracter==';'||caracter==':'||caracter=='?'||caracter=='/'||caracter=='>'||caracter=='<'||caracter==','||caracter==')'||caracter=='A'||caracter=='B'||caracter=='C'||caracter=='D'||caracter=='E'||caracter=='F'||caracter=='G'||caracter=='H'||caracter=='I'||caracter=='J'||caracter=='K'||caracter=='L'||caracter=='M'||caracter=='N'||caracter=='O'||caracter=='P'||caracter=='Q'||caracter=='R'||caracter=='S'||caracter=='T'||caracter=='U'||caracter=='V'||caracter=='W'||caracter=='X'||caracter=='Y'||caracter=='Z')
    {
    
        evt.consume();
    }
    
        
        if((tf1.getText().equals(""))&&(caracter=='.'))
                {
               tf1.setText("0");
               tf1.requestFocus();
                
                }
        
        if(!(tf1.getText()).equals(""))
        {
      
        
            String s=tf1.getText();
            
            int l=s.length();
            
          for(int i=0;i<l;i++)
            {
            
            if(s.charAt(i)=='.')
            {
               j=1;  
           
            }
           
            
            
            }
 if(j==1 && caracter=='.')
 {
 
                 evt.consume();
 
 }
 else if (((caracter < '0') || (caracter > '9'))
                        &&(caracter != '\b')&&(caracter != '.')) 
              {
                   
                    evt.consume();
                    
                 
                }
  

        
        }

        

    }//GEN-LAST:event_tf1KeyTyped

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed

        
        if(tf1.getText().equals(""))
           
               {
       
       
       l12.setText("null");
       l13.setText("null");
       l14.setText("null");
       l15.setText("null");
       l16.setText("null");
       l17.setText("null");
       l18.setText("null");
       l19.setText("null");
       l20.setText("null");
       
       tf1.setText("");
       tf1.requestFocus();
       
       
       
       
       } 
        else
        {
     if(cb.getSelectedItem().equals("Seconds"))
        {
        
            //Seconds
           Double a=Double.parseDouble(tf1.getText()); 
           Double ms=a*1000.0;
              l12.setText(String.valueOf(ms));
           Double s=a;
              l13.setText(String.valueOf(s));
           Double min=a*0.01666666666667;
              l14.setText(String.valueOf(min));
           Double hr=a*0.0002777777777778;
              l15.setText(String.valueOf(hr));
           Double day=a*0.00001157407407407;
              l16.setText(String.valueOf(day)); 
           Double week=a*0.000001653439153439;
              l17.setText(String.valueOf(week));
           Double mon=a*3.802537330419E-7;
              l18.setText(String.valueOf(mon));
           Double yr=a*3.170979198377E-8;
              l19.setText(String.valueOf(yr));
           Double cen=a*3.170979198377E-10;
              l20.setText(String.valueOf(cen));
            
          }
        
       else if(cb.getSelectedItem().equals("Minutes"))
        {
        
            //Seconds
            Double a=Double.parseDouble(tf1.getText());
           Double ms=a*60000.0;
              l12.setText(String.valueOf(ms));
           Double s=a*60;
              l13.setText(String.valueOf(s));
           Double min=a;
              l14.setText(String.valueOf(min));
           Double hr=a*0.01666666666667;
              l15.setText(String.valueOf(hr));
           Double day=a*0.0006944444444444;
              l16.setText(String.valueOf(day)); 
           Double week=a*0.00009920634920635;
              l17.setText(String.valueOf(week));
           Double mon=a*0.00002281522398251;
              l18.setText(String.valueOf(mon));
           Double yr=a*0.000001902587519026;
              l19.setText(String.valueOf(yr));
           Double cen=a*1.902587519026E-8;
              l20.setText(String.valueOf(cen));
            
          }

        else if(cb.getSelectedItem().equals("Hours"))
        {
        
            //Seconds
            Double a=Double.parseDouble(tf1.getText());
           Double ms=a*3600000;
              l12.setText(String.valueOf(ms));
           Double s=a*3600;
              l13.setText(String.valueOf(s));
           Double min=a*60.0;
              l14.setText(String.valueOf(min));
           Double hr=a;
              l15.setText(String.valueOf(hr));
           Double day=a*0.04166666666667;
              l16.setText(String.valueOf(day)); 
           Double week=a*0.005952380952381;
              l17.setText(String.valueOf(week));
           Double mon=a*0.001368913438951;
              l18.setText(String.valueOf(mon));
           Double yr=a*0.0001141552511416;
              l19.setText(String.valueOf(yr));
           Double cen=a*0.000001141552511416;
              l20.setText(String.valueOf(cen));
            
          }
        
        else if(cb.getSelectedItem().equals("Days"))
        {
        
            //Seconds
            Double a=Double.parseDouble(tf1.getText());
           Double ms=a*86400000.0;
              l12.setText(String.valueOf(ms));
           Double s=a*86400.0;
              l13.setText(String.valueOf(s));
           Double min=a*1440.0;
              l14.setText(String.valueOf(min));
           Double hr=a*24.0;
              l15.setText(String.valueOf(hr));
           Double day=a;
              l16.setText(String.valueOf(day)); 
           Double week=a*0.1428571428571;
              l17.setText(String.valueOf(week));
           Double mon=a*0.03285392253482;
              l18.setText(String.valueOf(mon));
           Double yr=a*0.002739726027397;
              l19.setText(String.valueOf(yr));
           Double cen=a*0.00002739726027397;
              l20.setText(String.valueOf(cen));
            
          }
        
        else if(cb.getSelectedItem().equals("Weeks"))
        {
        
            //Seconds
            Double a=Double.parseDouble(tf1.getText());
           Double ms=a*604800000.0;
              l12.setText(String.valueOf(ms));
           Double s=a*604800.0;
              l13.setText(String.valueOf(s));
           Double min=a*10080.0;
              l14.setText(String.valueOf(min));
           Double hr=a*168.0;
              l15.setText(String.valueOf(hr));
           Double day=a*7.0;
              l16.setText(String.valueOf(day)); 
           Double week=a;
              l17.setText(String.valueOf(week));
           Double mon=a*0.2299774577438;
              l18.setText(String.valueOf(mon));
           Double yr=a*0.01917808219178;
              l19.setText(String.valueOf(yr));
           Double cen=a*0.0001917808219178;
              l20.setText(String.valueOf(cen));
            
          }
        
        else if(cb.getSelectedItem().equals("Months"))
        {
        
            //Seconds
            Double a=Double.parseDouble(tf1.getText());
           Double ms=a*2629822965.84;
              l12.setText(String.valueOf(ms));
           Double s=a*2629822.96584;
              l13.setText(String.valueOf(s));
           Double min=a*43830.382764;
              l14.setText(String.valueOf(min));
           Double hr=a*730.5063794;
              l15.setText(String.valueOf(hr));
           Double day=a*30.43776580833;
              l16.setText(String.valueOf(day)); 
           Double week=a*4.348252258333;
              l17.setText(String.valueOf(week));
           Double mon=a;
              l18.setText(String.valueOf(mon));
           Double yr=a*0.08339113920091;
              l19.setText(String.valueOf(yr));
           Double cen=a*0.0008339113920091;
              l20.setText(String.valueOf(cen));
            
          }
        
        else if(cb.getSelectedItem().equals("Years"))
        {
        
            //Seconds
            Double a=Double.parseDouble(tf1.getText());
           Double ms=a*31536000000.0;
              l12.setText(String.valueOf(ms));
           Double s=a*31536000.0;
              l13.setText(String.valueOf(s));
           Double min=a*525600.0;
              l14.setText(String.valueOf(min));
           Double hr=a*8760.0;
              l15.setText(String.valueOf(hr));
           Double day=a*365.0;
              l16.setText(String.valueOf(day)); 
           Double week=a*52.14285714286;
              l17.setText(String.valueOf(week));
           Double mon=a*11.99168172521;
              l18.setText(String.valueOf(mon));
           Double yr=a;
              l19.setText(String.valueOf(yr));
           Double cen=a*0.1;
              l20.setText(String.valueOf(cen));
            
          }
        else if(cb.getSelectedItem().equals("Centuries"))
        {
        
            //Seconds
            Double a=Double.parseDouble(tf1.getText());
           Double ms=a*3153600000000.0;
              l12.setText(String.valueOf(ms));
           Double s=a*3153600000.0;
              l13.setText(String.valueOf(s));
           Double min=a*52560000.0;
              l14.setText(String.valueOf(min));
           Double hr=a*876000.0 ;
              l15.setText(String.valueOf(hr));
           Double day=a*36500.0;
              l16.setText(String.valueOf(day)); 
           Double week=a*5214.285714286;
              l17.setText(String.valueOf(week));
           Double mon=a*1199.168172521;
              l18.setText(String.valueOf(mon));
           Double yr=a*100.0;
              l19.setText(String.valueOf(yr));
           Double cen=a;
              l20.setText(String.valueOf(cen));
            
          }
        else
        {
        Double a=Double.parseDouble(tf1.getText());
        Double ms=a;
              l12.setText(String.valueOf(ms));
           Double s=a*0.001;
              l13.setText(String.valueOf(s));
           Double min=a*0.00001666666666667;
              l14.setText(String.valueOf(min));
           Double hr=a*2.777777777778E-7 ;
              l15.setText(String.valueOf(hr));
           Double day=a*1.157407407407E-8;
              l16.setText(String.valueOf(day)); 
           Double week=a*1.653439153439E-9;
              l17.setText(String.valueOf(week));
           Double mon=a*3.802537330419E-10;
              l18.setText(String.valueOf(mon));
           Double yr=a*3.170979198377E-11   ;
              l19.setText(String.valueOf(yr));
           Double cen=a*3.170979198377E-13;
              l20.setText(String.valueOf(cen));
        
    }
        }
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed

       l12.setText("");
       l13.setText("");
       l14.setText("");
       l15.setText("");
       l16.setText("");
       l17.setText("");
       l18.setText("");
       l19.setText("");
       l20.setText("");
       
       tf1.setText("");
       tf1.requestFocus();
       
    }//GEN-LAST:event_b2ActionPerformed

    private void b1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b1KeyPressed
      
        if(evt.getKeyCode()==evt.VK_ENTER)
        {
        
        if(tf1.getText().equals(""))
           
               {
       
       
       l12.setText("null");
       l13.setText("null");
       l14.setText("null");
       l15.setText("null");
       l16.setText("null");
       l17.setText("null");
       l18.setText("null");
       l19.setText("null");
       l20.setText("null");
       
       tf1.setText("");
       tf1.requestFocus();
       
       
       
       
       } 
        else
        {
     if(cb.getSelectedItem().equals("Seconds"))
        {
        
            //Seconds
           Double a=Double.parseDouble(tf1.getText()); 
           Double ms=a*1000.0;
              l12.setText(String.valueOf(ms));
           Double s=a;
              l13.setText(String.valueOf(s));
           Double min=a*0.01666666666667;
              l14.setText(String.valueOf(min));
           Double hr=a*0.0002777777777778;
              l15.setText(String.valueOf(hr));
           Double day=a*0.00001157407407407;
              l16.setText(String.valueOf(day)); 
           Double week=a*0.000001653439153439;
              l17.setText(String.valueOf(week));
           Double mon=a*3.802537330419E-7;
              l18.setText(String.valueOf(mon));
           Double yr=a*3.170979198377E-8;
              l19.setText(String.valueOf(yr));
           Double cen=a*3.170979198377E-10;
              l20.setText(String.valueOf(cen));
            
          }
        
       else if(cb.getSelectedItem().equals("Minutes"))
        {
        
            //Seconds
            Double a=Double.parseDouble(tf1.getText());
           Double ms=a*60000.0;
              l12.setText(String.valueOf(ms));
           Double s=a*60;
              l13.setText(String.valueOf(s));
           Double min=a;
              l14.setText(String.valueOf(min));
           Double hr=a*0.01666666666667;
              l15.setText(String.valueOf(hr));
           Double day=a*0.0006944444444444;
              l16.setText(String.valueOf(day)); 
           Double week=a*0.00009920634920635;
              l17.setText(String.valueOf(week));
           Double mon=a*0.00002281522398251;
              l18.setText(String.valueOf(mon));
           Double yr=a*0.000001902587519026;
              l19.setText(String.valueOf(yr));
           Double cen=a*1.902587519026E-8;
              l20.setText(String.valueOf(cen));
            
          }

        else if(cb.getSelectedItem().equals("Hours"))
        {
        
            //Seconds
            Double a=Double.parseDouble(tf1.getText());
           Double ms=a*3600000;
              l12.setText(String.valueOf(ms));
           Double s=a*3600;
              l13.setText(String.valueOf(s));
           Double min=a*60.0;
              l14.setText(String.valueOf(min));
           Double hr=a;
              l15.setText(String.valueOf(hr));
           Double day=a*0.04166666666667;
              l16.setText(String.valueOf(day)); 
           Double week=a*0.005952380952381;
              l17.setText(String.valueOf(week));
           Double mon=a*0.001368913438951;
              l18.setText(String.valueOf(mon));
           Double yr=a*0.0001141552511416;
              l19.setText(String.valueOf(yr));
           Double cen=a*0.000001141552511416;
              l20.setText(String.valueOf(cen));
            
          }
        
        else if(cb.getSelectedItem().equals("Days"))
        {
        
            //Seconds
            Double a=Double.parseDouble(tf1.getText());
           Double ms=a*86400000.0;
              l12.setText(String.valueOf(ms));
           Double s=a*86400.0;
              l13.setText(String.valueOf(s));
           Double min=a*1440.0;
              l14.setText(String.valueOf(min));
           Double hr=a*24.0;
              l15.setText(String.valueOf(hr));
           Double day=a;
              l16.setText(String.valueOf(day)); 
           Double week=a*0.1428571428571;
              l17.setText(String.valueOf(week));
           Double mon=a*0.03285392253482;
              l18.setText(String.valueOf(mon));
           Double yr=a*0.002739726027397;
              l19.setText(String.valueOf(yr));
           Double cen=a*0.00002739726027397;
              l20.setText(String.valueOf(cen));
            
          }
        
        else if(cb.getSelectedItem().equals("Weeks"))
        {
        
            //Seconds
            Double a=Double.parseDouble(tf1.getText());
           Double ms=a*604800000.0;
              l12.setText(String.valueOf(ms));
           Double s=a*604800.0;
              l13.setText(String.valueOf(s));
           Double min=a*10080.0;
              l14.setText(String.valueOf(min));
           Double hr=a*168.0;
              l15.setText(String.valueOf(hr));
           Double day=a*7.0;
              l16.setText(String.valueOf(day)); 
           Double week=a;
              l17.setText(String.valueOf(week));
           Double mon=a*0.2299774577438;
              l18.setText(String.valueOf(mon));
           Double yr=a*0.01917808219178;
              l19.setText(String.valueOf(yr));
           Double cen=a*0.0001917808219178;
              l20.setText(String.valueOf(cen));
            
          }
        
        else if(cb.getSelectedItem().equals("Months"))
        {
        
            //Seconds
            Double a=Double.parseDouble(tf1.getText());
           Double ms=a*2629822965.84;
              l12.setText(String.valueOf(ms));
           Double s=a*2629822.96584;
              l13.setText(String.valueOf(s));
           Double min=a*43830.382764;
              l14.setText(String.valueOf(min));
           Double hr=a*730.5063794;
              l15.setText(String.valueOf(hr));
           Double day=a*30.43776580833;
              l16.setText(String.valueOf(day)); 
           Double week=a*4.348252258333;
              l17.setText(String.valueOf(week));
           Double mon=a;
              l18.setText(String.valueOf(mon));
           Double yr=a*0.08339113920091;
              l19.setText(String.valueOf(yr));
           Double cen=a*0.0008339113920091;
              l20.setText(String.valueOf(cen));
            
          }
        
        else if(cb.getSelectedItem().equals("Years"))
        {
        
            //Seconds
            Double a=Double.parseDouble(tf1.getText());
           Double ms=a*31536000000.0;
              l12.setText(String.valueOf(ms));
           Double s=a*31536000.0;
              l13.setText(String.valueOf(s));
           Double min=a*525600.0;
              l14.setText(String.valueOf(min));
           Double hr=a*8760.0;
              l15.setText(String.valueOf(hr));
           Double day=a*365.0;
              l16.setText(String.valueOf(day)); 
           Double week=a*52.14285714286;
              l17.setText(String.valueOf(week));
           Double mon=a*11.99168172521;
              l18.setText(String.valueOf(mon));
           Double yr=a;
              l19.setText(String.valueOf(yr));
           Double cen=a*0.1;
              l20.setText(String.valueOf(cen));
            
          }
        else if(cb.getSelectedItem().equals("Centuries"))
        {
        
            //Seconds
            Double a=Double.parseDouble(tf1.getText());
           Double ms=a*3153600000000.0;
              l12.setText(String.valueOf(ms));
           Double s=a*3153600000.0;
              l13.setText(String.valueOf(s));
           Double min=a*52560000.0;
              l14.setText(String.valueOf(min));
           Double hr=a*876000.0 ;
              l15.setText(String.valueOf(hr));
           Double day=a*36500.0;
              l16.setText(String.valueOf(day)); 
           Double week=a*5214.285714286;
              l17.setText(String.valueOf(week));
           Double mon=a*1199.168172521;
              l18.setText(String.valueOf(mon));
           Double yr=a*100.0;
              l19.setText(String.valueOf(yr));
           Double cen=a;
              l20.setText(String.valueOf(cen));
            
          }
        else
        {
        Double a=Double.parseDouble(tf1.getText());
        Double ms=a;
              l12.setText(String.valueOf(ms));
           Double s=a*0.001;
              l13.setText(String.valueOf(s));
           Double min=a*0.00001666666666667;
              l14.setText(String.valueOf(min));
           Double hr=a*2.777777777778E-7 ;
              l15.setText(String.valueOf(hr));
           Double day=a*1.157407407407E-8;
              l16.setText(String.valueOf(day)); 
           Double week=a*1.653439153439E-9;
              l17.setText(String.valueOf(week));
           Double mon=a*3.802537330419E-10;
              l18.setText(String.valueOf(mon));
           Double yr=a*3.170979198377E-11   ;
              l19.setText(String.valueOf(yr));
           Double cen=a*3.170979198377E-13;
              l20.setText(String.valueOf(cen));
        
    }
        }
        
        
        
        }
        
        
    }//GEN-LAST:event_b1KeyPressed

    private void b2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b2KeyPressed
        
        if(evt.getKeyCode()==evt.VK_ENTER)
        {
         l12.setText("");
       l13.setText("");
       l14.setText("");
       l15.setText("");
       l16.setText("");
       l17.setText("");
       l18.setText("");
       l19.setText("");
       l20.setText("");
       
       tf1.setText("");
       tf1.requestFocus();
        
        }
    }//GEN-LAST:event_b2KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tcon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tcon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tcon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tcon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tcon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JComboBox cb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l12;
    private javax.swing.JLabel l13;
    private javax.swing.JLabel l14;
    private javax.swing.JLabel l15;
    private javax.swing.JLabel l16;
    private javax.swing.JLabel l17;
    private javax.swing.JLabel l18;
    private javax.swing.JLabel l19;
    private javax.swing.JLabel l20;
    private javax.swing.JTextField tf1;
    // End of variables declaration//GEN-END:variables
}
